RealEstate/Web/RealEstate.Web/Components/PopulatedPlaceViewComponent.cs
namespace RealEstate.Web.Components
{
    using Microsoft.AspNetCore.Mvc;

    using RealEstate.Services.Data.Interfaces;
    using RealEstate.Web.ViewModels.PopulatedPlaces;

    public class PopulatedPlaceViewComponent : ViewComponent
    {
        private readonly IPopulatedPlaceService populatedPlaceService;

        public PopulatedPlaceViewComponent(IPopulatedPlaceService populatedPlaceService)
        {
            this.populatedPlaceService = populatedPlaceService;
        }

        public IViewComponentResult Invoke(int locationId)
        {
            var model = this.populatedPlaceService
                .GetPopulatedPlacesByLocationId<PopulatedPlaceViewModel>((int)locationId);

            return this.View(model);
        }
    }
}

RealEstate/Web/RealEstate.Web/Controllers/PropertyController.cs
namespace RealEstate.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Hangfire;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Configuration;

    using RealEstate.Data.Models;
    using RealEstate.Services.Data.Interfaces;
    using RealEstate.Services.Interfaces;
    using RealEstate.Web.ViewModels.Locations;
    using RealEstate.Web.ViewModels.PopulatedPlaces;
    using RealEstate.Web.ViewModels.Property;
    using RealEstate.Web.ViewModels.PropertyTypes;
    using RealEstate.Web.ViewModels.Search;

    using static RealEstate.Common.GlobalConstants.Properties;

    public class PropertyController : BaseController
    {
        private readonly IBackgroundJobClient backgroundJobClient;
        private readonly IBuildingTypeService buildingTypeService;
        private readonly IConditionService conditionService;
        private readonly IDetailService detailService;
        private readonly IEquipmentService equipmentService;
        private readonly IHeatingService heatingService;
        private readonly ILocationService locationService;
        private readonly IPaginationService paginationService;
        private readonly IPropertyService propertyService;
        private readonly IPopulatedPlaceService populatedPlaceService;
        private readonly IPropertyTypeService propertyTypeService;
        private readonly IPropertyGetService propertyGetService;
        private readonly IImageService imageService;
        private readonly IConfiguration configuration;
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly UserManager<ApplicationUser> userManager;

        public PropertyController(IBackgroundJobClient backgroundJobClient,
            IBuildingTypeService buildingTypeService,
            IConditionService conditionService,
            IDetailService detailService,
            IEquipmentService equipmentService,
            IHeatingService heatingService,
            ILocationService locationService,
            IPaginationService paginationService,
            IPropertyService propertyService,
            IPopulatedPlaceService populatedPlaceService,
            IPropertyTypeService propertyTypeService,
            IPropertyGetService propertyGetService,
            IImageService imageService,
            IConfiguration configuration,
            SignInManager<ApplicationUser> signInManager, UserManager<ApplicationUser> userManager)
        {
            this.backgroundJobClient = backgroundJobClient;
            this.buildingTypeService = buildingTypeService;
            this.conditionService = conditionService;
            this.detailService = detailService;
            this.equipmentService = equipmentService;
            this.heatingService = heatingService;
            this.locationService = locationService;
            this.paginationService = paginationService;
            this.propertyService = propertyService;
            this.populatedPlaceService = populatedPlaceService;
            this.propertyTypeService = propertyTypeService;
            this.propertyGetService = propertyGetService;
            this.imageService = imageService;
            this.configuration = configuration;
            this.signInManager = signInManager;
            this.userManager = userManager;
        }

        [HttpGet]
        [Route("/add")]
        public async Task<IActionResult> AddAsync() => this.View(await this.SetCollectionsAsync(new PropertyInputModel()));

        [HttpPost]
        [Route("/add")]
        public async Task<IActionResult> AddAsync(PropertyInputModel property)
        {
            var errors = this.propertyService.PropertyValidator(property);
            this.AddModelStateErrors(errors);

            if (!this.ModelState.IsValid)
            {
                return this.View(await this.SetCollectionsAsync(property));
            }

            await this.propertyService.AddAsync(property, this.UserId);

            return this.RedirectToAction(nameof(this.Success));
        }

        [HttpPost]
        public async Task<IActionResult> Activate(int propertyId)
        {
            var property = await this.propertyGetService.GetByIdWithExpiredUserPropertiesAsync<PropertyEditViewModel>(propertyId, this.UserId);

            if (property == null)
            {
                throw new ArgumentNullException();
            }

            if (property.IsExpired == false || property.ExpirationDays > 0)
            {
                throw new InvalidOperationException();
            }

            property.ExpirationDays = 30;

            return await this.EditAsync(property);
        }

        [HttpGet]
        [Route("/edit")]
        public async Task<IActionResult> EditAsync(int propertyId)
        {
            var editModel = await this.propertyGetService.GetByIdWithExpiredUserPropertiesAsync<PropertyEditViewModel>(propertyId, this.UserId);

            if (editModel == null)
            {
                //TODO: Not found call administrator!
                return this.NotFound("Not found from EditGet");
            }

            editModel.BuildingType.IsChecked = true;
            editModel.PropertyTypes = this.propertyTypeService.Get<PropertyTypeViewModel>();
           //editModel.Locations = this.locationService.Get<LocationViewModel>();
            editModel.BuildingTypes = this.buildingTypeService.GetAll();
            editModel.Images = await this.imageService.GetAllByPropertyIdAsync(editModel.Id);

            foreach (var buildingType in editModel.BuildingTypes)
            {
                if (buildingType.Id == editModel.BuildingType.Id)
                {
                    buildingType.IsChecked = true;
                }
            }

            editModel.LocationId = editModel.PopulatedPlace.Location.Id;

            this.ViewBag.IsEdit = true;
            return this.View(editModel);
        }

        [HttpPost]
        [Route("/edit")]
        public async Task<IActionResult> EditAsync(PropertyEditViewModel editModel)
        {
            if (!await this.propertyService.IsUserPropertyAsync(editModel.Id, this.UserId))
            {
                //TODO: Not found call administrator!
                return this.NotFound("This is not your Property");
            }

            if (editModel.BuildingTypes != null)
            {
                if (editModel.BuildingTypes.Where(b => b.IsChecked).Count() > 1)
                {
                    this.ModelState.AddModelError("", "Canot check more than one building type!");
                }
            }

            if (!this.ModelState.IsValid)
            {
                editModel.PropertyTypes = this.propertyTypeService.Get<PropertyTypeViewModel>();
               // editModel.Locations = this.locationService.Get<LocationViewModel>();
                editModel.BuildingTypes = this.buildingTypeService.GetAll();

                editModel.PopulatedPlace = this.populatedPlaceService.GetPopulatedPlacesByProperty<PopulatedPlaceViewModel>(editModel.PopulatedPlaceId);
                editModel.LocationId = editModel.PopulatedPlace.Location.Id;

                return this.View(editModel);
            }

            await this.propertyService.EditAsync(editModel);

            var returnUrlCookieValue = this.Request.Cookies["ReturnUrl"];

            if (returnUrlCookieValue == null || this.propertyGetService.GetAllExpiredUserPropertiesCount(this.UserId) == 0)
            {
                return this.RedirectToMyActiveProperties();
            }

            return this.Redirect(returnUrlCookieValue);
        }

        [HttpPost]
        [AllowAnonymous]
        public IActionResult GetPopulatedPlaces(int? locationId)
        {
            if (locationId == null || locationId <= 0)
            {
                throw new InvalidOperationException("Invalid operation!");
            }

            var populatedPlaces = this.populatedPlaceService.GetPopulatedPlacesByLocationId<PopulatedPlaceViewModel>((int)locationId);

            return this.Json(new { data = populatedPlaces });
        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Index(int optionId, int page = 1)
        {
            var key = this.configuration["ApiKeys:ImgBBApiKey"];
            var key2 = this.configuration["ApiKeys:SendGridApiKey"];

            try
            {
                var allPropertiesCount = this.propertyGetService.GetAllActiveCount();
                var paginationModel = this.paginationService.CreatePagination(allPropertiesCount, PropertiesPerPage, page, this.ControllerName(nameof(PropertyController)), nameof(this.Index));

                var propertyIndexModel = new PropertyIndexModel
                {
                    Properties = this.propertyGetService.GetAllByOptionIdPerPage<PropertyViewModel>(optionId, paginationModel.CurrentPage),
                };

                propertyIndexModel.SearchInputModel = new SearchInputModel
                {
                    Locations = this.locationService.Get<LocationViewModel>(),
                };
                propertyIndexModel.CurrentOptionType = propertyIndexModel.OptionTypeModels.First(o => (int)o == optionId);

                this.ViewBag.Pager = paginationModel;

                return this.View(propertyIndexModel);
            }
            catch (Exception ex)
            {
                //TODO: Redirect to friedly error page
                return this.Content(ex.Message);
            }
        }

        [HttpGet]
        [AllowAnonymous]
        [Route("/Property/Single")]
        public async Task<IActionResult> PropertySingle(int id)
        {
            var propertyModel = await this.propertyGetService.GetByIdAsync<PropertyViewModel>(id);

RealEstate/Web/RealEstate.Web/Views/Shared/_LeftSideBarMenu.cshtml
<nav class="navbar navbar-default border-danger align-middle">
</nav>

RealEstate/Web/RealEstate.Web/Views/Shared/_Location.cshtml
@model PropertyInputModel

@*Location*@
<div class="form-group">
    <h1 style="font-size:large"><label asp-for="LocationId"></label></h1>
    <select asp-for="LocationId" class="form-select" id="location">
        <option value="">Select location</option>
        @foreach (var location in Model.Locations)
        {
            <optgroup>
                <option value="@location.Id">@location.Name</option>
            </optgroup>
        }
    </select>
    <span asp-validation-for="LocationId" class="text-danger"></span>
</div>
<br />

@*PopulatedPlace*@
<div class="form-group">
    <h1 style="font-size:large"><label asp-for="PopulatedPlaceId" id="PopulatedPlaceIdLabel"></label></h1>
    <select asp-for="PopulatedPlaceId" class="form-select" id="PopulatedPlaceId">
        <option value="">Select Populated place</option>
    </select>
    <span asp-validation-for="PopulatedPlaceId" class="text-danger"></span>
</div>
<br />

RealEstate/Web/RealEstate.Web/Views/Shared/_MainMenu.cshtml
<div class="navbar-collapse collapse justify-content-center" id="navbarDefault">
    <ul class="navbar-nav">

        <li class="nav-item">
            <a class="nav-link active" asp-area="" asp-controller="Home" asp-action="Index">@this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.HomePage))</a>
        </li>

        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Home" asp-action="Index">@this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.About))</a>
        </li>

        <li class="nav-item">
            <a class="nav-link " asp-area="" asp-controller="Property" asp-action="Index">@this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.Properties))</a>
        </li>

        <li class="nav-item">
            <a class="nav-link " href="blog-grid.html">@this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.Blog))</a>
        </li>

        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">@this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.Pages))</a>
            <div class="dropdown-menu">
                <a class="dropdown-item " asp-area="" asp-controller="Property" asp-action="Add">Add Property</a>
                <a class="dropdown-item " href="agents-grid.html">Agents Grid</a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link " href="contact.html">@this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.Contact))</a>
        </li>
    </ul>
</div>

RealEstate/Web/RealEstate.Web/Views/Shared/_MoreDetails.cshtml
@model PropertyInputModel

<h1 style="font-size:large">@this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.Condition))</h1>
<div class="row">
    @for (int i = 0; i < Model.BuildingTypes.Count; i++)
    {
        <div class="col-4">
            <input asp-for="Conditions[i].IsChecked" class="form-check-input" />
            <input asp-for="Conditions[i].Id" type="hidden" />
            <label class="form-check-label">@Model.Conditions[i].Name</label>
        </div>
    }
    <br />
    <br />
</div>

<h1 style="font-size:large">@this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.Equipments))</h1>
<div class="row">
    @for (int i = 0; i < Model.Equipments.Count; i++)
    {
        <div class="col-4">
            <input asp-for="Equipments[i].IsChecked" class="form-check-input" />
            <input asp-for="Equipments[i].Id" type="hidden" />
            <label class="form-check-label">@Model.Equipments[i].Name</label>
        </div>
    }
    <br />
    <br />
</div>

<h1 style="font-size:large">@this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.Heating))</h1>
<div class="row">
    @for (int i = 0; i < Model.Heatings.Count; i++)
    {
        <div class="col-4">
            <input asp-for="Heatings[i].IsChecked" class="form-check-input" />
            <input asp-for="Heatings[i].Id" type="hidden" />
            <label class="form-check-label">@Model.Heatings[i].Name</label>
        </div>
    }
    <br />
    <br />
</div>

<h1 style="font-size:large">@this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.Details))</h1>
<div class="row">
    @for (int i = 0; i < Model.Details.Count; i++)
    {
        <div class="col-4">
            <input asp-for="Details[i].IsChecked" class="form-check-input" />
            <input asp-for="Details[i].Id" type="hidden" />
            <label class="form-check-label">@Model.Details[i].Name</label>
        </div>
    }
    <br />
    <br />
</div>

RealEstate/Web/RealEstate.Web/Views/Shared/_PaginationPartial.cshtml
@model PaginationModel

<nav aria-label="...">
    <ul class="pagination justify-content-center">

        @if (Model.PreviousPage > 0)
        {
            if (Model.PreviousPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-page="@Model.FirstPage" tabindex="-1">First</a>
                </li>
            }

            <li class="page-item enabled">
                <a class="page-link" asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-page="@Model.PreviousPage" tabindex="-1">Previous</a>
            </li>
        }

        @for (int i = Pagination.PaginationMaxPages / 2; i >= 1; i--)
        {
            var previesPage = Model.CurrentPage - i;
            if (previesPage > 0)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-page="@previesPage" tabindex="-1">@previesPage</a>
                </li>
            }
        }

        <li class="page-item active">
            <a class="page-link" href="#">@Model.CurrentPage<span class="sr-only"></span></a>
        </li>

        @for (int i = 0; i < Pagination.PaginationMaxPages / 2; i++)
        {
            var nextPage = Model.NextPage + i;
            if (nextPage <= Model.LastPage)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-page="@nextPage" tabindex="-1">@nextPage</a>
                </li>
            }
        }   

        @if (Model.LastPage > Model.CurrentPage)
        {
            <li class="page-item">
                <a class="page-link" asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-page="@Model.NextPage">Next</a>
            </li>
            <li class="page-item">
                <a class="page-link" asp-controller="@Model.ControllerName" asp-action="@Model.ActionName" asp-route-page="@Model.LastPage" tabindex="-1">Last</a>
            </li>
        }
    </ul>
</nav>

RealEstate/Web/RealEstate.Web/Views/Shared/_PopulatedPlacePartial.cshtml
@model BasePropertyModel
@{
    var isEdit = this.ViewBag.IsEdit;

    if (isEdit == null)
    {
        isEdit = false;
    }
}

<div class="form-group" id="PopulatedPlacesHide">
    <h1 style="font-size:large">
        <label id="PopulatedPlaceIdLabel">
            @this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.PopulatedPlace))
        </label>
    </h1>
    <select asp-for="PopulatedPlaceId" class="form-select" id="PopulatedPlaceId">
        @if (isEdit)
        {
            <option value="@Model.PopulatedPlaceId">@Model.PopulatedPlace.Name</option>
            @await Component.InvokeAsync("PopulatedPlace", new { locationId = Model.LocationId })
        }
        else
        {
            <option value="0">@this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.SelectPopulatedPlace))</option>
        }
    </select>
    <span asp-validation-for="PopulatedPlaceId" class="text-danger"></span>
</div>

RealEstate/Web/RealEstate.Web/Views/Shared/_PropertyDescriptionPartial.cshtml
@model BasePropertyModel

<div class="form-group">
    <h1 style="font-size:large">
        <label>
            @this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.Description))
        </label>
    </h1>
    <textarea class="form-control" asp-for="Description" rows="4"
              placeholder=" @this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.MoreInfo))">
                </textarea>
</div>

RealEstate/Web/RealEstate.Web/Views/Shared/_PropertyExpDaysPartial.cshtml
@model BasePropertyModel
@{
    var plusDays = ' ';
    if (Model.ExpirationDays > 0)
    {
        plusDays = '+';
    }
}
<div class="col-3">
    <h1 style="font-size:large">
        <label>
            @this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.ExpirationDays))
        </label>
    </h1>
    <select class="form-select" asp-for="ExpirationDays">
        <option value="@GlobalConstants.Properties.ExpDays0">@plusDays@GlobalConstants.Properties.ExpDays0 days</option>
        <option value="@GlobalConstants.Properties.ExpDays30">@plusDays@GlobalConstants.Properties.ExpDays30 days</option>
        <option value="@GlobalConstants.Properties.ExpDays60">@plusDays@GlobalConstants.Properties.ExpDays60 days</option>
        <option value="@GlobalConstants.Properties.ExpDays90">@plusDays@GlobalConstants.Properties.ExpDays90 days</option>
    </select>
    <span asp-validation-for="ExpirationDays" class="text-danger"></span>
</div>

RealEstate/Web/RealEstate.Web/Views/Shared/_PropertyLinksPartial.cshtml
@model PropertyViewModel

@Html.AntiForgeryToken()
<div class="col-lg-12">

    <button class="btn btn-link"
            data-toggle="tooltip"
            data-placement="top"
            title="Редактирай"
            id="editLink">
        <a asp-area="" asp-controller="Property" asp-action="Edit" asp-route-propertyId="@Model.Id">
            <i class="bi bi-pencil link-primary col-3" style="font-size: 20px;"> </i>
        </a>
    </button>

    <div class="btn btn-link color-d"
         data-toggle="tooltip"
         data-placement="bottom"
         title="Изтрий">
        <a onclick="RemoveProperty('@Model.Id')">
            <i class="bi bi-trash3 link-danger col-3" style="font-size: 20px;"></i>
        </a>
    </div>

    <div class="btn btn-link color-d"
         data-toggle="tooltip"
         data-placement="bottom"
         title="Продаден">
        <a onclick="('@Model.Id')">
            <i class="bi bi-check2-all" style="font-size: 20px;"></i>
        </a>
    </div>

    @if (Model.IsExpired)
    {
        <form method="post" asp-controller="Property" asp-action="Activate" asp-route-propertyId="@Model.Id">
            <button class="btn btn-link color-b"
                    data-toggle="tooltip"
                    data-placement="top"
                    title="Активирай">
                <i class="bi bi-check-circle" style="font-size: 23px;" id="activate"></i>
            </button>
        </form>
    }
</div>
<br>

RealEstate/Web/RealEstate.Web/Views/Shared/_PropertyOptionsPartial.cshtml
@model BasePropertyModel
@{
    var isEdit = this.ViewBag.IsEdit;

    if (isEdit == null)
    {
        isEdit = false;
    }
}

<div class="form-group">
    <h1 style="font-size:large">
        <label>
            @this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.Options))
        </label>
    </h1>
    <div class="form-check-inline">
        <input class="form-check-input" type="radio" name="Option" id="Option" value="sale" checked>
        <label class="form-check-label">
            @this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.Sale))
        </label>
    </div>
    <div class="form-check-inline">
        <input class="form-check-input" type="radio" name="Option" id="Option" value="rent">
        <label class="form-check-label">
            @this.translateService.TranslateTo(CurrentSystemLanguage, nameof(BaseLanguage.Rent))
        </label>
    </div>
</div>

RealEstate/Web/RealEstate.Web/Views/Shared/_PropertyViewPartial.cshtml
@model IEnumerable<PropertyViewModel>

@{
    var isFromMyProperties = this.ViewBag.IsFromMyProperties;

    if (isFromMyProperties == null)
    {
        isFromMyProperties = false;
    }
}
<div class="container-fluid">
    <div class="row">
        <partial name="_LeftSideBarMenu" />
        @foreach (var property in Model)
        {
            <div class="col-md-3 col-sm-12 col-lg-4" id="@property.Id">
                @if (isFromMyProperties)
                {
                   <partial name="_PropertyLinksPartial" model="property" />
                }
                <div class="card-box-a card-shadow">
                    <div class="img-box-a">
                        <img src="@property.Images.FirstOrDefault().Url" alt="" class="img-a img-fluid">
                    </div>
                    <div class="card-overlay">
                        <div class="card-overlay-a-content">
                            <div class="card-header-a">
                                <h2 class="card-title-a">
                                    <a asp-area="" asp-controller="Property" asp-action="PropertySingle" asp-route-id="@property.Id">
                                        @property.PropertyTypeName
                                        <br /> @property.PopulatedPlace.Location.Name
                                    </a>
                                </h2>
                            </div>
                            <div class="card-body-a">
                                <div class="price-box d-flex">
                                    <p class="intro-subtitle intro-price">
                                        <span class="price-a">@property.Option | @property.PriceFormat())</span>
                                    </p>
                                </div>
                                @if (isFromMyProperties)
                                {
                                    <div class="price-box d-flex">
                                        @if (property.ExpirationDays <= 0)
                                        {
                                            <span class="price-a text-bg-danger"> @property.ExpireMessage</span>
                                        }
                                        else
                                        {
                                            <span class="price-a text-bg-danger">
                                                Expired after:
                                                @property.ExpirationDays
                                            </span>
                                        }
                                    </div>
                                }
                                else
                                {
                                    <a asp-area="" asp-controller="Property" asp-action="PropertySingle" asp-route-id="@property.Id" class="link-a">
                                        Click here to view
                                        <span class="bi bi-chevron-right"></span>
                                    </a>
                                }
                            </div>
                            <div class="card-footer-a">
                                <ul class="card-info d-flex justify-content-around">
                                    <li>
                                        <h4 class="card-info-title">Area</h4>
                                        <span>
                                            @property.Size<span>m</span>
                                            <sup>2</sup>
                                        </span>
                                    </li>
                                    <li>
                                        <h4 class="card-info-title">Beds</h4>
                                        <span>@property.TotalBedRooms</span>
                                    </li>
                                    <li>
                                        <h4 class="card-info-title">Baths</h4>
                                        <span>@property.TotalBathRooms</span>
                                    </li>
                                    <li>
                                        <h4 class="card-info-title">Garages</h4>
                                        <span>@property.TotalGarages</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

RealEstate/Web/RealEstate.Web/Views/Shared/_SearchForm.cshtml
@using RealEstate.Data.Models
@model SearchInputModel

<div class="container-fluid">
    <div class="row">
        <div class="col-md-9 col-lg-6 col-sm-12 justify-content-center offset-md-2 offset-lg-3">
            <form method="post" class="form-a" id="searchForm">
                @Html.AntiForgeryToken()
                <div asp-validation-summary=All class="text-danger"></div>
                <div class="row">
                    <div class="col-md-12 mb-2">
                        <div class="form-group">
                            <label asp-for="KeyWord" class="pb-2">Keyword</label>
                            <input asp-for="KeyWord" class="form-control form-control-lg form-control-a" placeholder="Keyword">
                        </div>
                    </div>
                    <br />
                    <br />
                    <br />
                    <br />
                    <vc:Locations model="@Model"></vc:Locations>
                    <br />
                    <br />
                    <br />
                    <br />
                    <partial name="_PopulatedPlacePartial" />

                    <div class="col-md-6 mb-2">
                        <div class="form-group mt-3">
                            <label asp-for=Type class="pb-2"></label>
                            <select asp-for=Type class="form-control form-select form-control-a">
                                <option value="">Select Option Type</option>
                                <option value="@PropertyOption.Sale">@PropertyOption.Sale</option>
                                <option value="@PropertyOption.Rent">@PropertyOption.Rent</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6 mb-2">
                        <div class="form-group mt-3">
                            <label asp-for="BedRooms" class="pb-2"></label>
                            <input asp-for="BedRooms" class="form-control" placeholder="Total BedRooms" />
                        </div>
                    </div>
                    <div class="col-md-6 mb-2">
                        <div class="form-group mt-3">
                            <label asp-for=Garages class="pb-2"></label>
                            <input asp-for="Garages" class="form-control" placeholder="Total Garages" />
                        </div>
                    </div>
                    <div class="col-md-6 mb-2">
                        <div class="form-group mt-3">
                            <label asp-for=BathRooms class="pb-2"></label>
                            <input asp-for="BathRooms" class="form-control" placeholder="Total BathRooms" />
                        </div>
                    </div>
                    <div class="col-md-6 mb-2">
                        <div class="form-group mt-3">
                            <input asp-for="MinPrice" class="form-control" placeholder="Min price" />
                        </div>
                        <div class="form-group mt-3">
                            <input asp-for="MaxPrice" class="form-control" placeholder="Max price" />
                        </div>
                        <br>
                    </div>
                    <br>
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-b" asp-controller="Property" asp-action="Search">Search Property</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>